library(data.table)
library(tidyr)
library(ggplot2)
library(mapview)
library(sf)
library(plyr)
library(corrplot)
library(zoo)


all_stations_summer_runoff <- readRDS('~/eda_eu_rivers/data/all_stations_summer_runoff.rds')
all_stations_winter_runoff <- readRDS('~/eda_eu_rivers/data/all_stations_winter_runoff.rds')
change_in_ratio <- readRDS('~/eda_eu_rivers/data/change_in_ratio.rds')
characteristic_1 <- readRDS('~/eda_eu_rivers/data/characteristic_1.rds')
characteristic_2 <- readRDS('~/eda_eu_rivers/data/characteristic_2.rds')
main_5_info <- readRDS('~/eda_eu_rivers/data/main_5_info.rds')
runoff_eu_year <- readRDS('~/eda_eu_rivers/data/runoff_eu_year.rds')
ratio_difference <- readRDS('~/eda_eu_rivers/data/ratio_difference.rds')
ratio_difference_2 <- readRDS('~/eda_eu_rivers/data/ratio_difference_2.rds')
rivers_5_info <- readRDS('~/eda_eu_rivers/data/rivers_5_info.rds')
runoff_5_rivers <- readRDS('~/eda_eu_rivers/data/runoff_5_rivers.rds')
runoff_5_rivers_2 <- readRDS('~/eda_eu_rivers/data/runoff_5_rivers_2.rds')
runoff_char <- readRDS('~/eda_eu_rivers/data/runoff_char.rds')
runoff_day_raw <- readRDS('~/eda_eu_rivers/data/runoff_day_raw.rds')
runoff_eu_day <- readRDS('~/eda_eu_rivers/data/runoff_eu_day.rds')
runoff_eu_info <- readRDS('~/eda_eu_rivers/data/runoff_eu_info.rds')
runoff_info_raw <- readRDS('~/eda_eu_rivers/data/runoff_info_raw.rds')
runoff_station_raw <- readRDS('~/eda_eu_rivers/data/runoff_station_raw.rds')
runoff_year_raw <- readRDS('~/eda_eu_rivers/data/runoff_year_raw.rds')
seasonal_discharge <- readRDS('~/eda_eu_rivers/data/seasonal_discharge.rds')
sum_year_discharge <- readRDS('~/eda_eu_rivers/data/sum_year_discharge.rds')
summer_runnof <- readRDS('~/eda_eu_rivers/data/summer_runnof.rds')
summer_winter <- readRDS('~/eda_eu_rivers/data/summer_winter.rds')
summer_winter_runnoff <- readRDS('~/eda_eu_rivers/data/summer_winter_runnoff.rds')
winter_runnof <- readRDS('~/eda_eu_rivers/data/winter_runnof.rds')
rivers_lovation <- readRDS('~/eda_eu_rivers/assigment/rivers_lovation.rds')
rivers_per_country <- readRDS('~/eda_eu_rivers/assigment/rivers_per_country.rds')
station_per_country <- readRDS('~/eda_eu_rivers/assigment/station_per_country.rds')
stations_per_river <- readRDS('~/eda_eu_rivers/assigment/stations_per_river.rds')
percentage_of_change <- readRDS('~/eda_eu_rivers/data/percentage_of_change.rds')
winter <- readRDS('~/eda_eu_rivers/data/winter.rds')
summer <-readRDS('~/eda_eu_rivers/data/summer.rds')
years <- readRDS('~/eda_eu_rivers/assigment/years.rds')
winter_1 <- readRDS('~/eda_eu_rivers/data/winter_1.rds')
summer_1 <- readRDS('~/eda_eu_rivers/data/summer_1.rds')

